apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetsample
  labels:
    app: aspnetsample
spec:
  replicas: 1
  template:
    metadata:
      name: aspnetsample
      labels:
        app: aspnetsample
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: sample
        image: bungle.azurecr.io/aspnetdemo:v1
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: .1
            memory: 300M
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: aspnetsample
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetsample
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: aspnetsample